www/protected/controllers/DirectorController.php
<?php
/**
 * Created by PhpStorm.
 * User: Дмитрий
 * Date: 14.01.14
 * Time: 0:01
 */

class DirectorController extends Controller
{
    public function actionView($id)
    {
        $this->render('view',array(
            'model'=>$this->loadModel($id),
        ));
    }

    public function actionManagers(){
        $model = new User();
        $model->unsetAttributes();

        if(isset($_GET['User']))
            $model->attributes=$_GET['User'];

        $this->render('index', array(
            'model' => $model,
        ));
    }

    public function actionAddmanager()
    {
        $model = new User();
        if(isset($_POST['User']))
        {
            $model->attributes = $_POST['User'];
            if ($model->validate() && $model->checkEmail($model->u_email) === true)
            {
                $model->u_type = 2;
                $model->save(false);
                $this->redirect($this->createUrl('director/managers'));
            }

        }
        $this->render('add_manager', array('model' => $model));
    }

    public function actionUpdate($id)
    {
        $model=$this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if(isset($_POST['User']))
        {
            $model->attributes=$_POST['User'];
            if($model->save())
                $this->redirect(array('view','id'=>$model->u_id));
        }

        $this->render('update',array(
            'model'=>$model,
        ));
    }

    public function actionDelete($id)
    {
        $this->loadModel($id)->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if(!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('director'));
    }
    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return User the loaded model
     * @throws CHttpException
     */
    public function loadModel($id)
    {
        $model=User::model()->findByPk($id);
        if($model===null)
            throw new CHttpException(404,'The requested page does not exist.');
        return $model;
    }
}
?>

www/protected/views/director/_form.php
<?php
/* @var $this UserController */
/* @var $model User */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'user-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'u_first_name'); ?>
		<?php echo $form->textField($model,'u_first_name',array('size'=>60,'maxlength'=>150)); ?>
		<?php echo $form->error($model,'u_first_name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'u_second_name'); ?>
		<?php echo $form->textField($model,'u_second_name',array('size'=>60,'maxlength'=>150)); ?>
		<?php echo $form->error($model,'u_second_name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'u_last_name'); ?>
		<?php echo $form->textField($model,'u_last_name',array('size'=>60,'maxlength'=>150)); ?>
		<?php echo $form->error($model,'u_last_name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'u_phone'); ?>
		<?php echo $form->textField($model,'u_phone',array('size'=>15,'maxlength'=>15)); ?>
		<?php echo $form->error($model,'u_phone'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'u_email'); ?>
		<?php echo $form->textField($model,'u_email',array('size'=>60,'maxlength'=>100)); ?>
		<?php echo $form->error($model,'u_email'); ?>
	</div>


	<div class="row">
		<?php echo $form->labelEx($model,'u_skype'); ?>
		<?php echo $form->textField($model,'u_skype',array('size'=>60,'maxlength'=>100)); ?>
		<?php echo $form->error($model,'u_skype'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'u_avatar'); ?>
		<?php echo $form->textField($model,'u_avatar',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'u_avatar'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'u_referer'); ?>
		<?php echo $form->textField($model,'u_referer',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'u_referer'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'u_discount'); ?>
		<?php echo $form->textField($model,'u_discount'); ?>
		<?php echo $form->error($model,'u_discount'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'u_type'); ?>
		<?php echo $form->dropDownList($model,'u_type',UserType::userTypes()); ?>
		<?php echo $form->error($model,'u_type'); ?>
	</div>

	<div class="row">
		<?php //echo $form->labelEx($model,'u_list'); ?>
		<?php //echo $form->dropDownList($model,'u_list', UserStatusList::userStatuses()); ?>
		<?php //echo $form->error($model,'u_list'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

www/protected/views/director/_manager_form.php
<?php
/**
 * Created by PhpStorm.
 * User: Дмитрий
 * Date: 14.01.14
 * Time: 10:25
 */ ?>

<?php
/* @var $this UserController */
/* @var $model User */
/* @var $form CActiveForm */
?>

<div class="form">

    <?php $form=$this->beginWidget('CActiveForm', array(
        'id'=>'addmanager',
        // Please note: When you enable ajax validation, make sure the corresponding
        // controller action is handling ajax validation correctly.
        // There is a call to performAjaxValidation() commented in generated controller code.
        // See class documentation of CActiveForm for details on this.
        'enableAjaxValidation'=>false,
    )); ?>

    <p class="note">Поля помеченные <span class="required">*</span> обязательны к заполнению.</p>

    <?php echo $form->errorSummary($model); ?>

    <div class="row">
        <?php echo $form->labelEx($model,'u_first_name'); ?>
        <?php echo $form->textField($model,'u_first_name',array('size'=>60,'maxlength'=>150)); ?>
        <?php echo $form->error($model,'u_first_name'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model,'u_second_name'); ?>
        <?php echo $form->textField($model,'u_second_name',array('size'=>60,'maxlength'=>150)); ?>
        <?php echo $form->error($model,'u_second_name'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model,'u_last_name'); ?>
        <?php echo $form->textField($model,'u_last_name',array('size'=>60,'maxlength'=>150)); ?>
        <?php echo $form->error($model,'u_last_name'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model,'u_email'); ?>
        <?php echo $form->textField($model,'u_email',array('size'=>60,'maxlength'=>100)); ?>
        <?php echo $form->error($model,'u_email'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model,'u_password'); ?>
        <?php echo $form->passwordField($model,'u_password',array('size'=>60,'maxlength'=>100)); ?>
        <?php echo $form->error($model,'u_password'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model,'u_phone'); ?>
        <?php echo $form->textField($model,'u_phone',array('size'=>15,'maxlength'=>15)); ?>
        <?php echo $form->error($model,'u_phone'); ?>
    </div>



    <div class="row buttons">
        <?php echo CHtml::submitButton($model->isNewRecord ? 'Добавить' : 'Save'); ?>
    </div>

    <?php $this->endWidget(); ?>

</div><!-- form -->

www/protected/views/director/add_manager.php
<?php
/**
 * Created by PhpStorm.
 * User: Дмитрий
 * Date: 14.01.14
 * Time: 10:17
 * @var $this DirectorController
 */
echo "<h1>Новый менеджер</h1>";
$this->renderPartial('_manager_form', array('model' => $model));
?>

www/protected/views/director/index.php
<?php
/**
 * Created by PhpStorm.
 * User: Дмитрий
 * Date: 14.01.14
 * Time: 0:15
 * @var $this DirectorController
 * @var $model User
 */
?>
<?php
    Yii::app()->clientScript->registerScript('search', "
    $('.search-button').click(function(){
        $('.search-form').toggle();
        return false;
    });
    $('.search-form form').submit(function(){
        $('#managers-grid').yiiGridView('update', {
            data: $(this).serialize()
        });
        return false;
    });
    ");
?>
<section class="table" style="margin-top: 0;">
    <div class="select-search-wrapper">
        <div class="yellow button add-manager"><a href="<?=$this->createUrl('director/addmanager')?>">Добавить менеджера</a></div>
        <div class="action-select">
            <span>С выделенными:</span>
            <select placeholder="Выберите макет">
                <option value="" default selected>Выберите действие</option>
                <option value="unblock">Разблокировать</option>
                <option value="block">Заблокировать</option>
            </select>
            <div class="yellow button make"><a href="#addmanager">Ок</a></div>
        </div>

        <div class="search-form">
         <?php
         $form=$this->beginWidget('CActiveForm', array(
            'action'=>Yii::app()->createUrl($this->route),
            'method'=>'get',
        ));
        ?>

        <div class="search">
            <!-- <input type="text" name="search" id="search" value=""> -->
            <?php echo $form->textField($model,'u_last_name', array('id' => "search", )); ?>
            <?php //echo CHtml::submitButton('', array('id' => 'search-submit')); ?>
            <button type="submit" name="submit" id="search-submit">
        </div>
        <?php $this->endWidget(); ?>
        </div>
    </div>


    <?php
    $this->widget('zii.widgets.grid.CGridView', array(
        'id' => 'managers-grid',
        'dataProvider' => $model->searchManagers(),
        'filter' => $model,
        'columns' => array(
            array(
                'name' => 'u_register_date',
                'header' => 'Дата регистрации',
                'type' => 'date',
                'value' => '$data->u_register_date',
                'filter' => true,
                //'search' => true,
            ),
            array(
                'name' => 'u_last_name',
                'header' => 'ФИО',
                'value' => '$data->getFio($data->u_id)',
                //'filter' => true,
            ),
            'u_email',
            'u_phone',

            array(
            'class' => 'CButtonColumn',
            ),
        ),
            'template'=>"{items}\n{pager}",
    ));

    ?>
    <span class="no-results">Ничего не найдено</span>
</section>

www/protected/views/director/update.php
<?php
/* @var $this UserController */
/* @var $model User */

$this->breadcrumbs=array(
	'Users'=>array('index'),
	$model->u_id=>array('view','id'=>$model->u_id),
	'Update',
);

$this->menu=array(
	array('label'=>'List User', 'url'=>array('index')),
	array('label'=>'Create User', 'url'=>array('create')),
	array('label'=>'View User', 'url'=>array('view', 'id'=>$model->u_id)),
	array('label'=>'Manage User', 'url'=>array('admin')),
);
?>

<h1>Update User <?php echo $model->u_id; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

www/protected/views/director/view.php
<?php
/**
 * Created by PhpStorm.
 * User: Дмитрий
 * Date: 14.01.14
 * Time: 10:14
 * @var $this DirectorController
 * @var $model User
 */
?>
<section class="account">
    <img src="<?= Yii::app()->getBaseUrl(true) ?>/img/userpic.png" class="userpic"/>
    <div class="info">
        <div class="main-info">
            <div style="overflow: hidden;">
                <span class="name"><?= $model->getFio($model->u_id)?></span>
                <div class="main-info-actions">
                    <a href="#mail" rel="leanModal"><img src="<?= Yii::app()->getBaseUrl(true) ?>/img/mail.png" /></a>
                    <a href="#delete-account" rel="leanModal"><img src="<?= Yii::app()->getBaseUrl(true) ?>/img/delete_account.png" /></a>
                </div>
            </div>
            <span class="date">Дата регистрации: <?= date("d-m-Y",$model->u_register_date) ?></span>
        </div>
        <div class="contact-money-info">
            <div>
                <span class="info-type">Email:</span><span class="info-content"><?= $model->u_email ?></span>
                </br>
                <span class="info-type">Телефон:</span><span class="info-content">+7 <?= $model->u_phone ?></span>
                </br>
                <span class="info-type">Skype:</span><span class="info-content"><?= $model->u_skype ?></span>
            </div>

        </div>
    </div>
</section>